site_name: Cavineers Software Learning
repo_url: https://github.com/cavineers/Learning
repo_name: Cavineers/Learning
theme:
  name: material

  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: material/git

  font:
    text: Roboto
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes

    - search.suggest
    - search.share

    - announce.dismiss

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: Cavineers/Learning
      branch: learningdevelopment

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Commands:
      - Commands/index.md 
      # - Page 1: section/page-1.md
      # ...
      # - Page n: section/page-n.md

    

  


