site_name: Cavineers Learning
repo_url: https://github.com/cavineers/Learning
repo_name: Cavineers/Learning
theme:
  name: material

  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: material/git

  font:
    text: Roboto
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.footer


    - search.suggest
    - search.share

    - announce.dismiss

    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html

  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  

nav:
  - Software:
    - Software/index.md
    - Basic:
      - Java basics:
        - Software/Java/index.md
        - Variables: Software/Java/variables.md
        - Classes: Software/Java/classes.md
        - Methods: Software/Java/methods.md
      - Robot:
        - Software/Subsystems/index.md
        - Building a Subsystem: Software/Subsystems/buildingASubsystem.md
        - Motors and Sensors: Software/Subsystems/motorsAndSensors.md
        - Motor States: Software/Subsystems/motorStates.md
        - Subsystem Variables: Software/Subsystems/subsystemVariables.md
      - Commands:
        - Software/Commands/index.md 
        - Structuring a Command: Software/Commands/structure.md
        - Properties of a Command: Software/Commands/properties.md
        - Command Composition:
          - Software/Commands/Composition/compositions.md
          - Compositional Types: Software/Commands/Composition/types.md
    - Git and Github: Software/gitAndGithub.md
      # ...
      # - Page n: section/page-n.md
    - Advanced:
      - Software/Advanced/index.md
      - PID Controllers: Software/Advanced/pid.md
      - Advanced java: 
        - Software/Java/advance.md
        - Inheritance: Software/Java/inheritance.md
        - Encapsulation: Software/Java/encapsulation.md

  - Hardware:
      - Hardware/index.md 
      # - Sensors:
      #   - Hardware/Sensors/index.md
      #   - Digital Sensors: Hardware/Sensors/digital.md
      #   - Analog Sensors: Hardware/Sensors/analog.md

  - Mechanical:
    - Mechanical/index.md 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cavineers
    

  


